name: Java Workflow
on: push 
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Installing Java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'
      - name: Maven Build
        run: mvn clean install
      - name: Checking Directory Structure
        run: ls        
      - name: Uploading Artificats
        uses: actions/upload-artifact@v4
        with:
          name: My-Artifacts
          path: |
            target/spring-boot-initial-0.0.1-SNAPSHOT.jar
  Deploy:
        needs: Build
        runs-on: ubuntu-latest
        steps:
          - name: Downloading the artifacts
            uses: actions/download-artifact@v4
            with:
                name: My-Artifacts
          - name: Checking the Directory
            run: ls
          - name: Deploy the artifacts
            run: echo "Deploy the artifacts"
         
